apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: dev    
            version: 8.5.1
            domain: "xxx.com"
            
  template:
    metadata:
      name: '{{cluster}}-elasticsearch'
    spec:
      syncPolicy:
        automated:
          selfHeal: true
          prune: false
        syncOptions:
          - Validate=true
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
          - ServerSideApply=true
      destination:
          namespace: logging
          name: '{{cluster}}'
      project: default
      source:
        repoURL: https://helm.elastic.co
        targetRevision: '{{version}}'
        chart: elasticsearch
        helm:
          values: |
            replicas: 1
            resources:
              requests:
                cpu: "100m"
                memory: "256Mi"
            secret:
              enabled: true
              password: "xxxx.123"
            ingress:
              enabled: true
              className: "nginx"
              annotations:
                cert-manager.io/cluster-issuer: "letsencrypt-prod"
                kubernetes.io/ingress.class: nginx
                nginx.ingress.kubernetes.io/backend-protocol: HTTPS
                nginx.ingress.kubernetes.io/ssl-redirect: "false"
              hosts:
                - host: elastic.{{domain}}
                  paths:
                    - path: /
              tls:
                - secretName: elasticsearch-tls
                  hosts:
                    - elastic.{{domain}}