{{- range $job := .Values.jobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ include "base-common.releaseName" $ }}-{{ $job.name }}"
  labels:
    {{- include "base-common.selectorLabels" $ | nindent 4 }}
spec:
  concurrencyPolicy: {{ $job.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ $job.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ include "base-common.releaseName" $ }}
            cron: {{ $job.name }}
        spec:
          {{- if hasKey $job "serviceAccount" }}
          serviceAccountName: {{ $job.serviceAccount.name | default $job.name }}
          {{- end }}
          {{- if hasKey $job "securityContext" }}
          securityContext:
            {{ toYaml $job.securityContext | indent 12 }}
          {{- end }}
          containers:
            - image: "{{ $job.image.repository }}:{{ $job.image.tag }}"
              imagePullPolicy: {{ $job.image.imagePullPolicy }}
              name: {{ $job.name }}
              {{- with $job.env }}
              env:
  {{ toYaml . | indent 16 }}
  {{- end }}
  {{- with $job.envFrom }}
envFrom:
  {{ toYaml . | indent 16 }}
  {{- end }}
  {{- if $job.command }}
command:
  {{ toYaml $job.command | indent 16 }}
  {{- end }}
  {{- with $job.args }}
args:
  {{ toYaml . | indent 16 }}
  {{- end }}
  {{- with $job.resources }}
resources:
  {{ toYaml . | indent 18 }}
  {{- end }}
  {{- with $job.volumeMounts }}
volumeMounts:
  {{ toYaml . | indent 16 }}
  {{- end }}
  {{- with $job.nodeSelector }}
nodeSelector:
  {{ toYaml . | indent 12 }}
  {{- end }}
  {{- with $job.affinity }}
affinity:
  {{ toYaml . | indent 12 }}
  {{- end }}
  {{- with $job.tolerations }}
tolerations:
  {{ toYaml . | indent 12 }}
  {{- end }}
restartPolicy: {{ $job.restartPolicy }}
  {{- with $job.volumes }}
volumes:
  {{ toYaml . | indent 12 }}
  {{- end }}
schedule: {{ $job.schedule | quote }}
successfulJobsHistoryLimit: {{ $job.successfulJobsHistoryLimit }}
  {{- end }}
