{{- if .Values.externalSecret }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecret.name }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.externalSecret.name }}
{{- end }}