apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-fluent-bit
  namespace: argocd
spec:
  project: default
  destination:
    namespace: logging
    name: prod
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ServerSideApply=true
  source:
    repoURL: https://fluent.github.io/helm-charts
    targetRevision: "0.48.9"
    chart: fluent-bit
    helm:
      values: |
        kind: DaemonSet
        replicaCount: 1
        image:
          repository: cr.fluentbit.io/fluent/fluent-bit
        service:
          type: ClusterIP
          port: 2020
        config:
          service: |
            [SERVICE]
                Daemon Off
                Flush 5
                Log_Level info
                Parsers_File /fluent-bit/etc/parsers.conf
                HTTP_Server On
                HTTP_Listen 0.0.0.0
                HTTP_Port 2020
                Health_Check On

          inputs: |
            [INPUT]
                Name tail
                Path /var/log/containers/*.log
                multiline.parser docker, cri
                Tag kube.*
                Mem_Buf_Limit 5MB
                Skip_Long_Lines On

          filters: |
            [FILTER]
                Name kubernetes
                Match kube.*
                Merge_Log On
                Keep_Log Off
                K8S-Logging.Parser On
                K8S-Logging.Exclude On
            [FILTER]
                Name grep
                Match kube.*
                Regex $kubernetes['namespace_name'] betx

          outputs: |
            [OUTPUT]
                Replace_Dots On
                Trace_Error       On
                Name es
                Match kube.*
                Host elastic.admingamehub.com
                Port 443
                HTTP_User elastic
                HTTP_Passwd Brgn9090.123
                tls On
                tls.verify On
                Logstash_Format On
                Logstash_Prefix prod
                Retry_Limit False
                Suppress_Type_Name On

  